config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'games#index'
  resources :games do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        
  has_many :games
  has_many :reviews
  validates :name, presence: true, length: { maximum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
  # before_action :configure_permitted_parameters, if: :devise_controller?

  # def configure_permitted_parameters
  #   added_attrs = [ :name, :email, :password, :password_confirmation ]
  #   devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
  #   devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  #   devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  # end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.includes(:user)
  end

  def new
    @game = Game.new
  end

  def create
    Game.create(game_params)
    redirect_to root_path
  end

  def edit
    @game = Game.find(params[:id])
  end

  def update
    game = Game.find(params[:id])
    game.update(game_params) if current_user.id == game.user_id
  end

  def show
    @game = Game.find(params[:id])
    @review = Review.new
    @reviews = @game.reviews.includes(:user)
  end

  def destroy
    game = Game.find(params[:id])
    game.destroy if current_user.id == game.user_id
  end

  private
  def game_params
    params.require(:game).permit(:title, :content, :image).merge(user_id: current_user.id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @game = Game.find(params[:game_id])
    @review = @game.reviews.new(review_params)
    @review.save
    respond_to do |format|
      format.html { redirect_to game_path(params[:game_id]) }
      format.json
    end
  end

  private
  def review_params
    params.require(:review).permit(:text).merge(user_id: current_user.id, game_id: params[:game_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/_game.html.haml
.main__box
  = image_tag("#{game.image}", class: "main__box__image")
  .main__box__info
    .main__box__info__title
      = link_to "#{game.title}", game_path(game.id), class: "main__box__info__title--link"
    .main__box__info__reviewer 
      = game.user.name

app/views/games/destroy.html.haml
.container
  .container__message 削除しました
  .container__btn
    = link_to "トップページへ戻る", root_path, class: "container__btn__text"
  

app/views/games/edit.html.haml
.container
  .container__text ゲームの情報に変更が必要ですか？
  = form_for @game, :html => { method: "patch", class: "container__form"} do |f|
    .container__form__title
      .container__form__title__up
        = f.label "タイトル", class: "container__form__title__up__text"
      .container__form__title__down
        = f.text_field :title, class: "container__form__title__down__input"
    .container__form__content
      .container__form__content__up
        = f.label "ゲームの内容、レビュー", class: "container__form__content__up__text"
      .container__form__content__down
        = f.text_area :content, class: "container__form__content__down__input"
    .container__form__image
      .container__form__image__up
        = f.label "イメージのURL", class: "container__form__image__up__text"
      .container__form__image__down
        = f.text_field :image, class: "container__form__image__down__input"
    = f.submit "更新する", class: "container__form__submit"

app/views/games/index.html.haml
.wrapper 
  .start
    .start__box
      %iframe(width="1440" height="900" src="https://www.youtube.com/embed/F3KNcS4vhFY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen)
    .start__box__welcome GetherGamersへようこそ
    .start__box__btn
      = link_to "ゲーム一覧へ", { anchor: "main"}, class: "start__box__btn--text"
    .start__header
      .start__header__contents
        - if user_signed_in?
          .start__header__contents--btn
            = link_to "Post Game", new_game_path, class: "start__header__contents--device--text"
          .start__header__contents--btn
            = link_to "Edit", edit_user_registration_path, class: "start__header__contents--device--text"
          .start__header__contents--btn
            = link_to "Log out", destroy_user_session_path, class: "start__header__contents--device--text"
        - else
          .start__header__contents--btn
            = link_to "Log in", new_user_session_path, class: "start__header__contents--device--text"
          .start__header__contents--btn
            = link_to "Sign up", new_user_registration_path, class: "start__header__contents--device--text"
  %section#main.main
    - @games.each do |game|
      = render partial: "game", locals: { game: game }

app/views/games/new.html.haml
.container
  .container__text お気に入りのゲームを投稿しましょう
  = form_for @game, :html => {:class => "container__form"} do |f|
    .container__form__title
      .container__form__title__up
        = f.label "タイトル", class: "container__form__title__up__text"
      .container__form__title__down
        = f.text_field :title, class: "container__form__title__down__input"
    .container__form__content
      .container__form__content__up
        = f.label "ゲームの内容、レビュー", class: "container__form__content__up__text"
      .container__form__content__down
        = f.text_area :content, class: "container__form__content__down__input"
    .container__form__image
      .container__form__image__up
        = f.label "イメージのURL", class: "container__form__image__up__text"
      .container__form__image__down
        = f.text_field :image, class: "container__form__image__down__input"
    = f.submit "投稿する", class: "container__form__submit"

app/views/games/show.html.haml
.content
  .content__above
    .content__above--title= @game.title
    - if user_signed_in? && current_user.id == @game.user_id
      .content__above--title--edit
        = link_to "編集", edit_game_path, class: "content__above--title--edit--text"
      .content__above--title--delete
        = link_to "削除", game_path, method: "delete", class: "content__above--title--delete--text"
  = image_tag("#{@game.image}", class: "content__image")
  .content__below
    .content__below__text= @game.content
    .content__below--top
      = link_to "トップへ戻る", root_path, class: "content__below--top--text"
  .content__text リアクション一覧
  .content__reviews
    - @reviews.each do |review|
      .content__reviews__review
        .content__reviews__review--text
          = review.text
        .content__reviews__review--name 
          = "reacted by #{review.user.name}"
  - if user_signed_in?
    = form_for @review, url: game_reviews_path(params[:id]), :html => {:class => "content__form"} do |f|
      .content__form__box
        = f.label "リアクションを投稿する", class: "content__form__box--label"
        .content__form__box__input
          = f.text_area :text, class: "content__form__box__input--text"
          = f.submit "投稿する", class: "content__form__box__input--submit"

app/views/games/update.html.haml
.container
  .container__message 内容を更新しました！
  .container__btn
    = link_to "トップページへ戻る", root_path, class: "container__btn__text"

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv":"Content-Type"}/
    %title GetherGamers
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true;
    = javascript_include_tag 'application', 'data-turbolinks-track': true;
  %body
    -# = render 'layouts/flash'
    = yield